set colorcolumn=80
set completeopt=menu,noinsert,noselect
set noexpandtab
set nohidden
set history=400
set laststatus=2
set lazyredraw
set nohlsearch
set noswapfile
set nowrap
set nowritebackup
set path=**
set nonumber
set norelativenumber
set scrolloff=8
set sidescrolloff=20
set smartindent
set splitbelow
set splitright
set tabstop=4
set shiftwidth=4
set updatetime=100
set signcolumn=yes
set list
set listchars=tab:\|\ ,eol:\\,nbsp:~,trail:-,
