# oh-my-zsh setup
export ZSH="$HOME/.oh-my-zsh"
export UPDATE_ZSH_DAYS=7
ZSH_THEME="../../.config/zsh/torbratsberg"
plugins=()
source $ZSH/oh-my-zsh.sh

if [ -z "$HOME/.cargo/env" ]; then
	source $HOME/.cargo/env
fi

# Exports
export GCM_CREDENTIAL_STORE=gpg
export GPG_TTY=$(tty)
export GOROOT=/usr/local/go
export GOPATH=$HOME/go
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/bingo:$PATH"
export PATH="$HOME/.bin:$PATH"
export PATH="/usr/bin:$PATH"
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

export LANG=en_US.UTF-8
export EDITOR='vim'
export NOTES_DIR="$HOME/main/notes"
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

TERM=xterm-256color

# Misc `cd` commands
alias m="cd $HOME/main"
alias c="cd $HOME/code"
alias co="cd $HOME/.config"
alias cdd="cd /mnt/c/Users/TORBRA/"

# Misc git shortcuts
alias gs="git status"
alias gc="git checkout"
alias gl="git log"
alias gd="git diff"
alias gll="git log --graph --stat --dirstat"
alias gp="git push"
alias gg="git pull"
alias gb="git branch"
alias gcb='git branch | fzf | xargs git checkout'
alias gcbo='git branch --remotes | fzf | xargs git checkout -t'
alias gbd='git branch | fzf | xargs git branch -D'
alias ga="git add"

alias nuke="rm -rf"
alias sshkey="cat $HOME/.ssh/id_rsa.pub | pbcopy"
alias l="lsd -la --icon never"

alias brofile="nvim $HOME/.config/zsh/zshrc"
alias brodate="source $HOME/.config/zsh/zshrc"

alias tu="tmux -f $HOME/.config/tmux/tmux.conf"
alias tur='tmux rename-window "$(basename ${PWD})"'

alias portswho="lsof -i -P -n | grep LISTEN"
alias fix_git_creds="gpgconf --kill gpg-agent && gpg-connect-agent reloadagent /bye"

HISTFILE=~/.config/zsh/.zsh_history

if [ -z "$HOME/.config/zsh/private-zshrc.sh" ]; then
	source "./private-zshrc.sh"
fi
