# oh-my-zsh setup
export ZSH="$HOME/.oh-my-zsh"
export UPDATE_ZSH_DAYS=7
ZSH_THEME="../../.config/zsh/torbratsberg"
plugins=()
source $ZSH/oh-my-zsh.sh

# Private rc file
if [ -z "$HOME/.config/zsh/private-zshrc.sh" ]; then
	source "$HOME/.config/zsh/private-zshrc.sh"
fi

source $HOME/.cargo/env

# Exports
export PATH=$PATH:/usr/local/go/bin
export GOPATH=$HOME/go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/bingo:$PATH"
export PATH="$HOME/.bin:$PATH"
export PATH="/usr/bin:$PATH"
export LANG=en_US.UTF-8
export EDITOR='nvim'
export NOTES_DIR="$HOME/main/notes"
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

TERM=xterm-256color

alias m="cd $HOME/main"
alias s="cd $HOME/sites"
alias t="cd wp-content/themes/"
alias p="cd wp-content/plugins/"
alias c="cd $HOME/code"
alias co="cd $HOME/.config"

alias gs="git status"
alias gl="git log --graph --stat --dirstat"

alias py3="python3"

alias nuke="rm -rf"
alias sshkey="cat $HOME/.ssh/id_rsa.pub | pbcopy"
alias vhosts="nvim /Applications/MAMP/conf/apache/extra/httpd-vhosts.conf"
alias hosts="sudo nvim /private/etc/hosts"
alias dev="bash $HOME/code/bash/dc-devkit/start.sh"
alias devv="node /Users/torbratsberg/work/dc-devkit/bin/index.js"
alias ip="ipconfig getifaddr en0"
alias l="lsd -la --icon never"
alias ungitplugins="find ./wp-content/plugins/ -type d -name ".git" -exec rm -rf "{}" \;"

alias brofile="nvim $HOME/.config/zsh/zshrc"
alias brodate="source $HOME/.config/zsh/zshrc"

alias tu="tmux -f $HOME/.config/tmux/tmux.conf"
alias sch="scripthub"

alias cds='__cds() { cd "$(fd -d 1 -t d | fzf)" && cd wp-content && cd "$(fd -d 2 -t d | fzf)"}; __cds '
alias tur='tmux rename-window "$(basename ${PWD})"'


alias gtc="~/go/bin/gitor_client"
alias nv="nvim"

alias portswho="lsof -i -P -n | grep LISTEN"

HISTFILE=~/.config/zsh/.zsh_history
